exclude: [Gemfile", "Gemfile.lock"]
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

url: "http://ambaboo.github.io" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap