exclude: [Gemfile", "Gemfile.lock"]
markdown: kramdown
kramdown:
  syntax_highlighter: rouge

url: "http://ambaboo.github.io" # the base hostname & protocol for your site
# Gems
gems: [jekyll-sitemap, rouge]