exclude: [Gemfile", "Gemfile.lock"]
# Conversion
markdown: kramdown
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

url: "http://ambaboo.github.io" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap